//
//  DataForApp.swift
//  MoliyaStudiyasi
//
//  Created by Luiza on 03.10.2020.
//  Copyright © 2020 Luiza. All rights reserved.
//

import Foundation

struct Constants {
    static let arrayNamesCode = ["adminCode", "famCode", "nalogCode", "trudCode", "grajdanskiyCode", "ugolovCode", "ugolovProcessCode", "tamojCode", "obshestvoCode", "zemelniyCode", "budjetCode", "chastniyCode"]
    
    static var sectionsForAdminCode = [Section(sectionsName: "adminCodeSec1",
                                               chapters: [Chapter(chapter: "adminCodeSec1Chap1", liked: false)],
                                               expanded: false),
                                       Section(sectionsName: "adminCodeSec2",
                                               chapters: ["adminCodeSec2Chap1",
                                                          "adminCodeSec2Chap2",
                                                          "adminCodeSec2Chap3",
                                                          "adminCodeSec2Chap4",
                                                          "adminCodeSec2Chap5",
                                                          "adminCodeSec2Chap6",
                                                          "adminCodeSec2Chap7",
                                                          "adminCodeSec2Chap8",
                                                          "adminCodeSec2Chap9",
                                                          "adminCodeSec2Chap10",
                                                          "adminCodeSec2Chap11",
                                                          "adminCodeSec2Chap12",
                                                          "adminCodeSec2Chap13",
                                                          "adminCodeSec2Chap14",
                                                          "adminCodeSec2Chap15",
                                                          "adminCodeSec2Chap16",
                                                          "adminCodeSec2Chap17"].map{ Chapter(chapter: $0, liked: false)},
                                               expanded: false),
                                       Section(sectionsName: "adminCodeSec3",
                                               chapters: ["adminCodeSec3Chap1",
                                                          "adminCodeSec3Chap2"].map{ Chapter(chapter: $0, liked: false)},
                                               expanded: false),
                                       Section(sectionsName: "adminCodeSec4",
                                               chapters: ["adminCodeSec4Chap1",
                                                          "adminCodeSec4Chap2",
                                                          "adminCodeSec4Chap3",
                                                          "adminCodeSec4Chap4",
                                                          "adminCodeSec4Chap5",
                                                          "adminCodeSec4Chap6",
                                                          "adminCodeSec4Chap7"].map{ Chapter(chapter: $0, liked: false)},
                                               expanded: false),
                                       Section(sectionsName: "adminCodeSec5",
                                               chapters: ["adminCodeSec5Chap1",
                                                          "adminCodeSec5Chap2",
                                                          "adminCodeSec5Chap3",
                                                          "adminCodeSec5Chap4",
                                                          "adminCodeSec5Chap5",
                                                          "adminCodeSec5Chap6",
                                                          "adminCodeSec5Chap7",
                                                          "adminCodeSec5Chap8"].map{ Chapter(chapter: $0, liked: false)},
                                               expanded: false)
    ]
    
    
    static var sectionsForFamilyCode = [Section(sectionsName: "famCodeSec1",
                                                chapters: ["famCodeSec1Chap1",
                                                           "famCodeSec1Chap2"].map{ Chapter(chapter: $0, liked: false)},
                                                expanded: false),
                                        Section(sectionsName: "famCodeSec2",
                                                chapters: ["famCodeSec2Chap1",
                                                           "famCodeSec2Chap2",
                                                           "famCodeSec2Chap3",
                                                           "famCodeSec2Chap4",
                                                           "famCodeSec2Chap5",
                                                           "famCodeSec2Chap6"].map{ Chapter(chapter: $0, liked: false)},
                                                expanded: false),
                                        Section(sectionsName: "famCodeSec3",
                                                chapters: ["famCodeSec3Chap1",
                                                           "famCodeSec3Chap2"].map{ Chapter(chapter: $0, liked: false)},
                                                expanded: false),
                                        Section(sectionsName: "famCodeSec4",
                                                chapters: ["famCodeSec4Chap1",
                                                           "famCodeSec4Chap2",
                                                           "famCodeSec4Chap3"].map{ Chapter(chapter: $0, liked: false)},
                                                expanded: false),
                                        Section(sectionsName: "famCodeSec5",
                                                chapters: ["famCodeSec5Chap1",
                                                           "famCodeSec5Chap2",
                                                           "famCodeSec5Chap3",
                                                           "famCodeSec5Chap4",
                                                           "famCodeSec5Chap5"].map{ Chapter(chapter: $0, liked: false)},
                                                expanded: false),
                                        Section(sectionsName: "famCodeSec6",
                                                chapters: ["famCodeSec6Chap1",
                                                           "famCodeSec6Chap2",
                                                           "famCodeSec6Chap3",
                                                           "famCodeSec6Chap4"].map{ Chapter(chapter: $0, liked: false)},
                                                expanded: false),
                                        Section(sectionsName: "famCodeSec7",
                                                chapters: ["famCodeSec7Chap1",
                                                           "famCodeSec7Chap2",
                                                           "famCodeSec7Chap3",
                                                           "famCodeSec7Chap4",
                                                           "famCodeSec7Chap5",
                                                           "famCodeSec7Chap6",
                                                           "famCodeSec7Chap7",
                                                           "famCodeSec7Chap8"].map{ Chapter(chapter: $0, liked: false)},
                                                expanded: false),
                                        Section(sectionsName: "famCodeSec8",
                                                chapters: ["famCodeSec8Chap1"].map{ Chapter(chapter: $0, liked: false)},
                                                expanded: false)]
    
    static var sectionsForTrudCode = [Section(sectionsName: "trudCodeSec1",
                                              chapters: ["trudCodeSec1Chap1",
                                                         "trudCodeSec1Chap2",
                                                         "trudCodeSec1Chap3",
                                                         "trudCodeSec1Chap4",
                                                         "trudCodeSec1Chap5",
                                                         "trudCodeSec1Chap6",
                                                         "trudCodeSec1Chap7",
                                                         "trudCodeSec1Chap8",
                                                         "trudCodeSec1Chap9",
                                                         "trudCodeSec1Chap10",
                                                         "trudCodeSec1Chap11",
                                                         "trudCodeSec1Chap12",
                                                         "trudCodeSec1Chap13",
                                                         "trudCodeSec1Chap14",
                                                         "trudCodeSec1Chap15",
                                                         "trudCodeSec1Chap16"
                                              ].map{ Chapter(chapter: $0, liked: false)},
                                              expanded: false)]
    
    static var sectionsForUgolovCode = [Section(sectionsName: "ugolovCodeSec1",
                                                chapters: ["ugolovCodeSec1Chap1",
                                                           "ugolovCodeSec1Chap2"
                                                ].map{ Chapter(chapter: $0, liked: false)},
                                                expanded: false),
                                        Section(sectionsName: "ugolovCodeSec2",
                                                chapters: ["ugolovCodeSec2Chap1",
                                                           "ugolovCodeSec2Chap2",
                                                           "ugolovCodeSec2Chap3",
                                                           "ugolovCodeSec2Chap4",
                                                           "ugolovCodeSec2Chap5",
                                                           "ugolovCodeSec2Chap6"
                                                ].map{ Chapter(chapter: $0, liked: false)},
                                                expanded: false),
                                        Section(sectionsName: "ugolovCodeSec3",
                                                chapters: [Chapter(chapter: "ugolovCodeSec3Chap1", liked: false)],
                                                expanded: false),
                                        Section(sectionsName: "ugolovCodeSec4",
                                                chapters: ["ugolovCodeSec4Chap1",
                                                           "ugolovCodeSec4Chap2"
                                                ].map{ Chapter(chapter: $0, liked: false)},
                                                expanded: false),
                                        Section(sectionsName: "ugolovCodeSec5",
                                                chapters: ["ugolovCodeSec5Chap1",
                                                           "ugolovCodeSec5Chap2",
                                                           "ugolovCodeSec5Chap3"
                                                ].map{ Chapter(chapter: $0, liked: false)},
                                                expanded: false),
                                        Section(sectionsName: "ugolovCodeSec6",
                                                chapters: ["ugolovCodeSec6Chap1",
                                                           "ugolovCodeSec6Chap2"
                                                ].map{ Chapter(chapter: $0, liked: false)},
                                                expanded: false),
                                        Section(sectionsName: "ugolovCodeSec7",
                                                chapters: [Chapter(chapter: "ugolovCodeSec7Chap1", liked: false)],
                                                expanded: false),
                                        Section(sectionsName: "ugolovCodeSec8",
                                                chapters: [Chapter(chapter: "ugolovCodeSec8Chap1", liked: false)],
                                                expanded: false)
                                        
    ]
    
    
    static var sectionsForTamojCode = [Section(sectionsName: "tamojCodeSec1",
                                               chapters: ["tamojCodeSec1Chap1",
                                                          "tamojCodeSec1Chap2",
                                                          "tamojCodeSec1Chap3",
                                               ].map{ Chapter(chapter: $0, liked: false)},
                                               expanded: false),
                                       Section(sectionsName: "tamojCodeSec2",
                                               chapters: ["tamojCodeSec2Chap1",
                                                          "tamojCodeSec2Chap2",
                                                          "tamojCodeSec2Chap3",
                                                          "tamojCodeSec2Chap4",
                                                          "tamojCodeSec2Chap5",
                                                          "tamojCodeSec2Chap6",
                                                          "tamojCodeSec2Chap7",
                                                          "tamojCodeSec2Chap8",
                                                          "tamojCodeSec2Chap9",
                                                          "tamojCodeSec2Chap10",
                                                          "tamojCodeSec2Chap11",
                                                          "tamojCodeSec2Chap12",
                                                          "tamojCodeSec2Chap13",
                                                          "tamojCodeSec2Chap14",
                                                          "tamojCodeSec2Chap15",
                                                          "tamojCodeSec2Chap16",
                                                          "tamojCodeSec2Chap17",
                                                          "tamojCodeSec2Chap18"
                                               ].map{ Chapter(chapter: $0, liked: false)},
                                               expanded: false),
                                       Section(sectionsName: "tamojCodeSec3",
                                               chapters: ["tamojCodeSec3Chap1",
                                                          "tamojCodeSec3Chap2",
                                                          "tamojCodeSec3Chap3",
                                                          "tamojCodeSec3Chap4",
                                                          "tamojCodeSec3Chap5"
                                               ].map{ Chapter(chapter: $0, liked: false)},
                                               expanded: false),
                                       Section(sectionsName: "tamojCodeSec4",
                                               chapters: ["tamojCodeSec4Chap1",
                                                          "tamojCodeSec4Chap2",
                                                          "tamojCodeSec4Chap3",
                                                          "tamojCodeSec4Chap4",
                                                          "tamojCodeSec4Chap5",
                                                          "tamojCodeSec4Chap6",
                                                          "tamojCodeSec4Chap7"
                                               ].map{ Chapter(chapter: $0, liked: false)},
                                               expanded: false),
                                       Section(sectionsName: "tamojCodeSec5",
                                               chapters: ["tamojCodeSec5Chap1",
                                                          "tamojCodeSec5Chap2"
                                               ].map{ Chapter(chapter: $0, liked: false)},
                                               expanded: false),
                                       Section(sectionsName: "tamojCodeSec6",
                                               chapters: ["tamojCodeSec6Chap1",
                                                          "tamojCodeSec6Chap2",
                                                          "tamojCodeSec6Chap3"
                                               ].map{ Chapter(chapter: $0, liked: false)},
                                               expanded: false),
                                       Section(sectionsName: "tamojCodeSec7",
                                               chapters: ["tamojCodeSec7Chap1",
                                                          "tamojCodeSec7Chap2",
                                                          "tamojCodeSec7Chap3"
                                               ].map{ Chapter(chapter: $0, liked: false)},
                                               expanded: false),
                                       Section(sectionsName: "tamojCodeSec8",
                                               chapters: ["tamojCodeSec8Chap1",
                                                          "tamojCodeSec8Chap2",
                                                          "tamojCodeSec8Chap3",
                                                          "tamojCodeSec8Chap4",
                                                          "tamojCodeSec8Chap5",
                                                          "tamojCodeSec8Chap6",
                                                          "tamojCodeSec8Chap7",
                                                          "tamojCodeSec8Chap8",
                                                          "tamojCodeSec8Chap9",
                                                          "tamojCodeSec8Chap10",
                                                          "tamojCodeSec8Chap11",
                                               ].map{ Chapter(chapter: $0, liked: false)},
                                               expanded: false),
                                       Section(sectionsName: "tamojCodeSec9",
                                               chapters: ["tamojCodeSec9Chap1",
                                                          "tamojCodeSec9Chap2",
                                                          "tamojCodeSec9Chap3",
                                                          "tamojCodeSec9Chap4"
                                               ].map{ Chapter(chapter: $0, liked: false)},
                                               expanded: false),
                                       Section(sectionsName: "tamojCodeSec10",
                                               chapters: ["tamojCodeSec10Chap1",
                                                          "tamojCodeSec10Chap2",
                                                          "tamojCodeSec10Chap3"
                                               ].map{ Chapter(chapter: $0, liked: false)},
                                               expanded: false),
                                       Section(sectionsName: "tamojCodeSec11",
                                               chapters: ["tamojCodeSec11Chap1"
                                               ].map{ Chapter(chapter: $0, liked: false)},
                                               expanded: false),
                                       Section(sectionsName: "tamojCodeSec12",
                                               chapters: ["tamojCodeSec12Chap1"
                                               ].map{ Chapter(chapter: $0, liked: false)},
                                               expanded: false)
    ]
    
    static var sectionsForBudgetCode = [Section(sectionsName: "budjetCodeSec1",
                                                chapters: ["budjetCodeSec1Chap1",
                                                           "budjetCodeSec1Chap2",
                                                           "budjetCodeSec1Chap3",
                                                           "budjetCodeSec1Chap4"
                                                ].map{ Chapter(chapter: $0, liked: false)},
                                                expanded: false),
                                        Section(sectionsName: "budjetCodeSec2",
                                                chapters: ["budjetCodeSec2Chap1",
                                                           "budjetCodeSec2Chap2"
                                                ].map{ Chapter(chapter: $0, liked: false)},
                                                expanded: false),
                                        Section(sectionsName: "budjetCodeSec3",
                                                chapters: ["budjetCodeSec3Chap1",
                                                           "budjetCodeSec3Chap2"
                                                ].map{ Chapter(chapter: $0, liked: false)},
                                                expanded: false),
                                        Section(sectionsName: "budjetCodeSec4",
                                                chapters: ["budjetCodeSec4Chap1",
                                                           "budjetCodeSec4Chap2",
                                                           "budjetCodeSec4Chap3"
                                                ].map{ Chapter(chapter: $0, liked: false)},
                                                expanded: false),
                                        Section(sectionsName: "budjetCodeSec5",
                                                chapters: ["budjetCodeSec5Chap1",
                                                           "budjetCodeSec5Chap2"
                                                ].map{ Chapter(chapter: $0, liked: false)},
                                                expanded: false),
                                        Section(sectionsName: "budjetCodeSec6",
                                                chapters: ["budjetCodeSec6Chap1",
                                                           "budjetCodeSec6Chap2",
                                                           "budjetCodeSec6Chap3"
                                                ].map{ Chapter(chapter: $0, liked: false)},
                                                expanded: false),
                                        Section(sectionsName: "budjetCodeSec7",
                                                chapters: ["budjetCodeSec7Chap1",
                                                           "budjetCodeSec7Chap2",
                                                           "budjetCodeSec7Chap3",
                                                           "budjetCodeSec7Chap4",
                                                           "budjetCodeSec7Chap5"
                                                ].map{ Chapter(chapter: $0, liked: false)},
                                                expanded: false),
                                        Section(sectionsName: "budjetCodeSec8",
                                                chapters: ["budjetCodeSec8Chap1",
                                                           "budjetCodeSec8Chap2",
                                                           "budjetCodeSec8Chap3",
                                                           "budjetCodeSec8Chap4",
                                                           "budjetCodeSec8Chap5"
                                                ].map{ Chapter(chapter: $0, liked: false)},
                                                expanded: false)
                                    
    ]
    
    static var sectionsForNalogCode = [Section(sectionsName: "nalogCodeSec1",
                                               chapters: ["nalogCodeSec1Chap1",
                                                          "nalogCodeSec1Chap2",
                                                          "nalogCodeSec1Chap3",
                                                          "nalogCodeSec1Chap4",
                                                          "nalogCodeSec1Chap5",
                                                          "nalogCodeSec1Chap6"
                                               ].map{ Chapter(chapter: $0, liked: false)},
                                               expanded: false),
                                       Section(sectionsName: "nalogCodeSec2",
                                               chapters: ["nalogCodeSec2Chap1",
                                                          "nalogCodeSec2Chap2"
                                               ].map{ Chapter(chapter: $0, liked: false)},
                                               expanded: false),
                                       Section(sectionsName: "nalogCodeSec3",
                                               chapters: ["nalogCodeSec3Chap1",
                                                          "nalogCodeSec3Chap2",
                                                          "nalogCodeSec3Chap3",
                                                          "nalogCodeSec3Chap4",
                                                          "nalogCodeSec3Chap5",
                                                          "nalogCodeSec3Chap6",
                                                          "nalogCodeSec3Chap7"
                                               ].map{ Chapter(chapter: $0, liked: false)},
                                               expanded: false),
                                       Section(sectionsName: "nalogCodeSec4",
                                               chapters: ["nalogCodeSec4Chap1"
                                               ].map{ Chapter(chapter: $0, liked: false)},
                                               expanded: false),
                                       Section(sectionsName: "nalogCodeSec5",
                                               chapters: ["nalogCodeSec5Chap1",
                                                          "nalogCodeSec5Chap2",
                                                          "nalogCodeSec5Chap3"
                                               ].map{ Chapter(chapter: $0, liked: false)},
                                               expanded: false),
                                       Section(sectionsName: "nalogCodeSec6",
                                               chapters: ["nalogCodeSec6Chap1",
                                                          "nalogCodeSec6Chap2",
                                                          "nalogCodeSec6Chap3",
                                                          "nalogCodeSec6Chap4",
                                                          "nalogCodeSec6Chap5",
                                                          "nalogCodeSec6Chap6"
                                               ].map{ Chapter(chapter: $0, liked: false)},
                                               expanded: false),
                                       Section(sectionsName: "nalogCodeSec7",
                                               chapters: ["nalogCodeSec7Chap1"
                                               ].map{ Chapter(chapter: $0, liked: false)},
                                               expanded: false),
                                       Section(sectionsName: "nalogCodeSec8",
                                               chapters: ["nalogCodeSec8Chap1",
                                                          "nalogCodeSec8Chap2",
                                                          "nalogCodeSec8Chap3"
                                               ].map{ Chapter(chapter: $0, liked: false)},
                                               expanded: false),
                                       Section(sectionsName: "nalogCodeSec9",
                                               chapters: ["nalogCodeSec9Chap1"
                                               ].map{ Chapter(chapter: $0, liked: false)},
                                               expanded: false),
                                       Section(sectionsName: "nalogCodeSec10",
                                               chapters: ["nalogCodeSec10Chap1",
                                                          "nalogCodeSec10Chap2",
                                                          "nalogCodeSec10Chap3",
                                                          "nalogCodeSec10Chap4",
                                                          "nalogCodeSec10Chap5",
                                                          "nalogCodeSec10Chap6",
                                                          "nalogCodeSec10Chap7",
                                                          "nalogCodeSec10Chap8",
                                                          "nalogCodeSec10Chap9"
                                               ].map{ Chapter(chapter: $0, liked: false)},
                                               expanded: false),
                                       Section(sectionsName: "nalogCodeSec11",
                                               chapters: ["nalogCodeSec11Chap1",
                                                          "nalogCodeSec11Chap2"
                                               ].map{ Chapter(chapter: $0, liked: false)},
                                               expanded: false),
                                       Section(sectionsName: "nalogCodeSec12",
                                               chapters: ["nalogCodeSec12Chap1",
                                                          "nalogCodeSec12Chap2",
                                                          "nalogCodeSec12Chap3",
                                                          "nalogCodeSec12Chap4",
                                                          "nalogCodeSec12Chap5",
                                                          "nalogCodeSec12Chap6",
                                                          "nalogCodeSec12Chap7",
                                                          "nalogCodeSec12Chap8",
                                                          "nalogCodeSec12Chap9",
                                                          "nalogCodeSec12Chap10"
                                               ].map{ Chapter(chapter: $0, liked: false)},
                                               expanded: false),
                                       Section(sectionsName: "nalogCodeSec13",
                                               chapters: ["nalogCodeSec13Chap1",
                                                          "nalogCodeSec13Chap2",
                                                          "nalogCodeSec13Chap3",
                                                          "nalogCodeSec13Chap4",
                                                          "nalogCodeSec13Chap5",
                                                          "nalogCodeSec13Chap6"
                                               ].map{ Chapter(chapter: $0, liked: false)},
                                               expanded: false),
                                       Section(sectionsName: "nalogCodeSec14",
                                               chapters: ["nalogCodeSec14Chap1"
                                               ].map{ Chapter(chapter: $0, liked: false)},
                                               expanded: false),
                                       Section(sectionsName: "nalogCodeSec15",
                                               chapters: ["nalogCodeSec15Chap1",
                                                          "nalogCodeSec15Chap2"
                                               ].map{ Chapter(chapter: $0, liked: false)},
                                               expanded: false),
                                       Section(sectionsName: "nalogCodeSec16",
                                               chapters: ["nalogCodeSec16Chap1",
                                                          "nalogCodeSec16Chap2"
                                               ].map{ Chapter(chapter: $0, liked: false)},
                                               expanded: false),
                                       Section(sectionsName: "nalogCodeSec17",
                                               chapters: ["nalogCodeSec17Chap1"
                                               ].map{ Chapter(chapter: $0, liked: false)},
                                               expanded: false),
                                       Section(sectionsName: "nalogCodeSec18",
                                               chapters: ["nalogCodeSec18Chap1"
                                               ].map{ Chapter(chapter: $0, liked: false)},
                                               expanded: false),
                                       Section(sectionsName: "nalogCodeSec19",
                                               chapters: ["nalogCodeSec19Chap1"
                                               ].map{ Chapter(chapter: $0, liked: false)},
                                               expanded: false),
                                       Section(sectionsName: "nalogCodeSec20",
                                               chapters: ["nalogCodeSec20Chap1"
                                               ].map{ Chapter(chapter: $0, liked: false)},
                                               expanded: false),
                                       Section(sectionsName: "nalogCodeSec21",
                                               chapters: ["nalogCodeSec21Chap1",
                                                          "nalogCodeSec21Chap2",
                                                          "nalogCodeSec21Chap3",
                                                          "nalogCodeSec21Chap4",
                                                          "nalogCodeSec21Chap5"
                                               ].map{ Chapter(chapter: $0, liked: false)},
                                               expanded: false)
                                       
    ]
    
    static var sectionsForZemelniyCode = [Section(sectionsName: "zemelniyCodeSec1",
                                                  chapters: ["zemelniyCodeSec1Chap1",
                                                             "zemelniyCodeSec1Chap2",
                                                             "zemelniyCodeSec1Chap3",
                                                             "zemelniyCodeSec1Chap4",
                                                             "zemelniyCodeSec1Chap5",
                                                             "zemelniyCodeSec1Chap6",
                                                             "zemelniyCodeSec1Chap7",
                                                             "zemelniyCodeSec1Chap8",
                                                             "zemelniyCodeSec1Chap9",
                                                             "zemelniyCodeSec1Chap10",
                                                             "zemelniyCodeSec1Chap11",
                                                             "zemelniyCodeSec1Chap12",
                                                             "zemelniyCodeSec1Chap13",
                                                             "zemelniyCodeSec1Chap14"
                                                  ].map{ Chapter(chapter: $0, liked: false)},
                                                  expanded: false)
    ]
    
    static var sectionsForObshestvoCode = [Section(sectionsName: "obshestvoCodeSec1",
                                                   chapters: ["obshestvoCodeSec1Chap1",
                                                              "obshestvoCodeSec1Chap2",
                                                              "obshestvoCodeSec1Chap3",
                                                              "obshestvoCodeSec1Chap4",
                                                              "obshestvoCodeSec1Chap5",
                                                              "obshestvoCodeSec1Chap6",
                                                              "obshestvoCodeSec1Chap7"
                                                   ].map{ Chapter(chapter: $0, liked: false)},
                                                   expanded: false)
    ]
    
    static var sectionsForUgolovProcessCode = [Section(sectionsName: "ugolovProcessCodeSec1",
                                                       chapters: ["ugolovProcessCodeSec1Chap1",
                                                                  "ugolovProcessCodeSec1Chap2"
                                                       ].map{ Chapter(chapter: $0, liked: false)},
                                                       expanded: false),
                                               Section(sectionsName: "ugolovProcessCodeSec2",
                                                       chapters: ["ugolovProcessCodeSec2Chap1",
                                                                  "ugolovProcessCodeSec2Chap2",
                                                                  "ugolovProcessCodeSec2Chap3",
                                                                  "ugolovProcessCodeSec2Chap4",
                                                                  "ugolovProcessCodeSec2Chap5",
                                                       ].map{ Chapter(chapter: $0, liked: false)},
                                                       expanded: false),
                                               Section(sectionsName: "ugolovProcessCodeSec3",
                                                       chapters: ["ugolovProcessCodeSec3Chap1",
                                                                  "ugolovProcessCodeSec3Chap2",
                                                                  "ugolovProcessCodeSec3Chap3",
                                                                  "ugolovProcessCodeSec3Chap4",
                                                                  "ugolovProcessCodeSec3Chap5",
                                                                  "ugolovProcessCodeSec3Chap6",
                                                                  "ugolovProcessCodeSec3Chap7",
                                                                  "ugolovProcessCodeSec3Chap8",
                                                                  "ugolovProcessCodeSec3Chap9",
                                                                  "ugolovProcessCodeSec3Chap10",
                                                                  "ugolovProcessCodeSec3Chap11",
                                                                  "ugolovProcessCodeSec3Chap12",
                                                                  "ugolovProcessCodeSec3Chap13",
                                                                  "ugolovProcessCodeSec3Chap14",
                                                                  "ugolovProcessCodeSec3Chap15",
                                                                  "ugolovProcessCodeSec3Chap16",
                                                                  "ugolovProcessCodeSec3Chap17",
                                                                  "ugolovProcessCodeSec3Chap18",
                                                                  "ugolovProcessCodeSec3Chap19"
                                                       ].map{ Chapter(chapter: $0, liked: false)},
                                                       expanded: false),
                                               Section(sectionsName: "ugolovProcessCodeSec4",
                                                       chapters: [        "ugolovProcessCodeSec4Chap1",
                                                                          "ugolovProcessCodeSec4Chap2",
                                                                          "ugolovProcessCodeSec4Chap3",
                                                                          "ugolovProcessCodeSec4Chap4",
                                                                          "ugolovProcessCodeSec4Chap5",
                                                                          "ugolovProcessCodeSec4Chap6",
                                                                          "ugolovProcessCodeSec4Chap7",
                                                                          "ugolovProcessCodeSec4Chap8"
                                                       ].map{ Chapter(chapter: $0, liked: false)},
                                                       expanded: false),
                                               Section(sectionsName: "ugolovProcessCodeSec5",
                                                       chapters: [         "ugolovProcessCodeSec5Chap1",
                                                                           "ugolovProcessCodeSec5Chap2",
                                                                           "ugolovProcessCodeSec5Chap3"
                                                       ].map{ Chapter(chapter: $0, liked: false)},
                                                       expanded: false),
                                               Section(sectionsName: "ugolovProcessCodeSec6",
                                                       chapters: [Chapter(chapter: "ugolovProcessCodeSec6Chap1", liked: false)],
                                                       expanded: false),
                                               Section(sectionsName: "ugolovProcessCodeSec7",
                                                       chapters: [         "ugolovProcessCodeSec7Chap1",
                                                                           "ugolovProcessCodeSec7Chap2",
                                                       ].map{ Chapter(chapter: $0, liked: false)},
                                                       expanded: false),
                                               Section(sectionsName: "ugolovProcessCodeSec8",
                                                       chapters: [         "ugolovProcessCodeSec8Chap1",
                                                                           "ugolovProcessCodeSec8Chap2",
                                                                           "ugolovProcessCodeSec8Chap3"
                                                       ].map{ Chapter(chapter: $0, liked: false)},
                                                       expanded: false),
                                               Section(sectionsName: "ugolovProcessCodeSec9",
                                                       chapters: [         "ugolovProcessCodeSec9Chap1",
                                                                           "ugolovProcessCodeSec9Chap2",
                                                                           "ugolovProcessCodeSec9Chap3",
                                                                           "ugolovProcessCodeSec9Chap4",
                                                                           "ugolovProcessCodeSec9Chap5",
                                                                           "ugolovProcessCodeSec9Chap6",
                                                                           "ugolovProcessCodeSec9Chap7"
                                                       ].map{ Chapter(chapter: $0, liked: false)},
                                                       expanded: false),
                                               Section(sectionsName: "ugolovProcessCodeSec10",
                                                       chapters: [         "ugolovProcessCodeSec10Chap1",
                                                                           "ugolovProcessCodeSec10Chap2",
                                                                           "ugolovProcessCodeSec10Chap3",
                                                                           "ugolovProcessCodeSec10Chap4",
                                                                           "ugolovProcessCodeSec10Chap5",
                                                                           "ugolovProcessCodeSec10Chap6",
                                                                           "ugolovProcessCodeSec10Chap7"
                                                       ].map{ Chapter(chapter: $0, liked: false)},
                                                       expanded: false),
                                               Section(sectionsName: "ugolovProcessCodeSec11",
                                                       chapters: [         "ugolovProcessCodeSec11Chap1",
                                                                           "ugolovProcessCodeSec11Chap2",
                                                                           "ugolovProcessCodeSec11Chap3",
                                                                           "ugolovProcessCodeSec11Chap4"
                                                       ].map{ Chapter(chapter: $0, liked: false)},
                                                       expanded: false),
                                               Section(sectionsName: "ugolovProcessCodeSec12",
                                                       chapters: [         "ugolovProcessCodeSec12Chap1",
                                                                           "ugolovProcessCodeSec12Chap2"
                                                       ].map{ Chapter(chapter: $0, liked: false)},
                                                       expanded: false),
                                               Section(sectionsName: "ugolovProcessCodeSec13",
                                                       chapters: [         "ugolovProcessCodeSec13Chap1",
                                                                           "ugolovProcessCodeSec13Chap2",
                                                                           "ugolovProcessCodeSec13Chap3",
                                                                           "ugolovProcessCodeSec13Chap4"
                                                       ].map{ Chapter(chapter: $0, liked: false)},
                                                       expanded: false),
                                               Section(sectionsName: "ugolovProcessCodeSec14",
                                                       chapters: [         "ugolovProcessCodeSec14Chap1",
                                                                           "ugolovProcessCodeSec14Chap2"
                                                       ].map{ Chapter(chapter: $0, liked: false)},
                                                       expanded: false)
    ]
    
    static var sectionsForGrajdanskiyCode = [Section(sectionsName: "grajdanskiyCodeSec1",
                                                     chapters: ["grajdanskiyCodeSec1Chap1",
                                                                "grajdanskiyCodeSec1Chap2",
                                                                "grajdanskiyCodeSec1Chap3",
                                                                "grajdanskiyCodeSec1Chap4",
                                                                "grajdanskiyCodeSec1Chap5",
                                                                "grajdanskiyCodeSec1Chap6",
                                                                "grajdanskiyCodeSec1Chap7",
                                                                "grajdanskiyCodeSec1Chap8",
                                                                "grajdanskiyCodeSec1Chap9",
                                                                "grajdanskiyCodeSec1Chap10",
                                                                "grajdanskiyCodeSec1Chap11",
                                                                "grajdanskiyCodeSec1Chap12"
                                                     ].map{ Chapter(chapter: $0, liked: false)},
                                                     expanded: false),
                                             Section(sectionsName: "grajdanskiyCodeSec2",
                                                     chapters: ["grajdanskiyCodeSec2Chap1",
                                                                "grajdanskiyCodeSec2Chap2",
                                                                "grajdanskiyCodeSec2Chap3",
                                                                "grajdanskiyCodeSec2Chap4",
                                                                "grajdanskiyCodeSec2Chap5",
                                                                "grajdanskiyCodeSec2Chap6",
                                                                "grajdanskiyCodeSec2Chap7"
                                                     ].map{ Chapter(chapter: $0, liked: false)},
                                                     expanded: false),
                                             Section(sectionsName: "grajdanskiyCodeSec3",
                                                     chapters: ["grajdanskiyCodeSec3Chap1",
                                                                "grajdanskiyCodeSec3Chap2",
                                                                "grajdanskiyCodeSec3Chap3",
                                                                "grajdanskiyCodeSec3Chap4",
                                                                "grajdanskiyCodeSec3Chap5",
                                                                "grajdanskiyCodeSec3Chap6",
                                                                "grajdanskiyCodeSec3Chap7",
                                                                "grajdanskiyCodeSec3Chap8",
                                                                "grajdanskiyCodeSec3Chap9"
                                                     ].map{ Chapter(chapter: $0, liked: false)},
                                                     expanded: false)
    ]
    
    static var sectionsForChastniyCode = [Section(sectionsName: "",
                                                  chapters: ["chastniyCodeSec1Chap1",
                                                             "chastniyCodeSec1Chap2",
                                                             "chastniyCodeSec1Chap3",
                                                             "chastniyCodeSec1Chap4",
                                                             "chastniyCodeSec1Chap5",
                                                             "chastniyCodeSec1Chap6"
                                                  ].map{ Chapter(chapter: $0, liked: false)},
                                                  expanded: false)
    ]
}
